/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mynative_MyNative */

#ifndef _Included_mynative_MyNative
#define _Included_mynative_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mynative_MyNative
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_mynative_MyNative_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     mynative_MyNative
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_mynative_MyNative_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     mynative_MyNative
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mynative_MyNative_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
